---
name: 'build container images (arm64)'

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ci-image-arm64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  toolchain:
    runs-on: oracle-vm-32cpu-128gb-arm64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-toolchain
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          target: toolchain
          cache-from: type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
          cache-to: type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          tags: ttl.sh/hadron-toolchain:${{ github.sha }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          target: toolchain
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-pr-${{ github.event.pull_request.number }}-arm64
          cache-to: type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-pr-${{ github.event.pull_request.number }}-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
  container:
    runs-on: oracle-vm-32cpu-128gb-arm64
    needs:
      - toolchain
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-container
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          target: container
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64
          cache-to: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          tags: ttl.sh/hadron-container:${{ github.sha }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          target: container
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-pr-${{ github.event.pull_request.number }}-arm64
          cache-to: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-pr-${{ github.event.pull_request.number }}-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
      - name: Test container image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          target: container-test
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-pr-${{ github.event.pull_request.number }}-arm64
          build-args: |
            ARCH=aarch64
            BUILD_ARCH=aarch64
  hadron-grub:
    runs-on: oracle-vm-32cpu-128gb-arm64
    needs:
      - container  # Take advantage of cached layers from the container build
    strategy:
      matrix:
        kernel: [ "cloud" ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry for cache
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}${{ matrix.kernel == 'cloud' && '-cloud' || '' }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:grub-${{ matrix.kernel }}-arm64
          cache-to: type=registry,ref=quay.io/kairos/hadron-build-cache:grub-${{ matrix.kernel }}-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3
          target: default
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
            ARCH=aarch64
            BUILD_ARCH=aarch64
      - name: Build PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ttl.sh/hadron${{ matrix.kernel == 'cloud' && '-cloud' || '' }}:${{ github.sha }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          target: default
          cache-from: |
            type=registry,ref=quay.io/kairos/hadron-build-cache:toolchain-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:container-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:grub-${{ matrix.kernel }}-arm64
            type=registry,ref=quay.io/kairos/hadron-build-cache:grub-${{ matrix.kernel }}-pr-${{ github.event.pull_request.number }}-arm64
          cache-to: type=registry,ref=quay.io/kairos/hadron-build-cache:grub-${{ matrix.kernel }}-pr-${{ github.event.pull_request.number }}-arm64,mode=max,ignore-error=true,compression=zstd,compression-level=3
          build-args: |
            BOOTLOADER=grub
            KERNEL_TYPE=${{ matrix.kernel }}
            ARCH=aarch64
            BUILD_ARCH=aarch64
  build-kairos-grub:
    runs-on: ubuntu-24.04-arm
    needs:
      - hadron-grub
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Download Dockerfile from kairos repository
        run: |
          mkdir -p build
          curl -sSL https://raw.githubusercontent.com/kairos-io/kairos/master/images/Dockerfile -o build/Dockerfile.kairos
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./build/Dockerfile.kairos
          push: true
          platforms: linux/arm64
          tags: ttl.sh/hadron-init-bios:${{ github.sha }}
          build-args: |
            BASE_IMAGE=ttl.sh/hadron-cloud:${{ github.sha }}
            VERSION=v0.0.1-${{ github.sha }}
            TRUSTED_BOOT=false
  build-grub-iso:
    runs-on: ubuntu-24.04-arm
    needs:
      - build-kairos-grub
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build ISO
        run: |
          mkdir build
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --platform=arm64 \
          -v $PWD/build/:/output \
          quay.io/kairos/auroraboot:v0.16.2 --debug build-iso --output /output/ \
          --override-name kairos-hadron-bios-${{ github.sha }} \
          docker:ttl.sh/hadron-init-bios:${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: kairos-hadron-bios-${{ github.sha }}.iso.zip
          path: build/*.iso

# This test requires changes onto PEG to support ARM architecture properly.
#  Uncomment when PEG supports ARM testing
#  tests-bios:
#    runs-on: ubuntu-24.04-arm
#    name: ${{ matrix.test }} tests
#    needs:
#      - build-grub-iso
#    if: github.event_name == 'pull_request'
#    strategy:
#      matrix:
#        test:
#          - "acceptance"
#          - "reset"
#          - "custom-partitioning"
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v6
#        with:
#          fetch-depth: 0
#      - name: Install Go
#        uses: actions/setup-go@v6
#        timeout-minutes: 5
#        with:
#          go-version-file: tests/go.mod
#          cache-dependency-path: tests/go.sum
#      - name: Download artifacts
#        uses: actions/download-artifact@v7
#        with:
#          name: kairos-hadron-bios-${{ github.sha }}.iso.zip
#      - name: Enable KVM group perms
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu-system qemu-system-aarch64 qemu-utils qemu-kvm acl udev mkisofs swtpm
#      - name: Run tests
#        env:
#          USE_QEMU: true
#          KVM: true
#          MEMORY: 5000
#          DRIVE_SIZE: 50000
#          CREATE_VM: true
#          CPUS: 4
#        run: |
#          export ISO=$PWD/$(ls *.iso|grep -v ipxe | head -1 )
#          echo "ISO is: $ISO"
#          cp tests/go.* .
#          go mod download
#          go run github.com/onsi/ginkgo/v2/ginkgo -v --fail-fast -r --label-filter "${{ matrix.test }}" ./tests/
#      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
#        if: failure()
#        with:
#          name: acceptance-${{github.sha}}.logs.zip
#          path: tests/**/logs/*
#          if-no-files-found: warn
